#!/usr/bin/env python

import sys
from torque_accounting import parser

def print_job(name,job):
    try:
        user=job['user']
        queue=job['events']['Q']
        start=job['events']['S']
        endt=job['events']['E']
        wait_time=job['wait_time']
        run_time=job['run_time']
        print "%-20s  %-10s  %s  %s  %s  %s  %s" % (name,user,queue,start,endt,wait_time,run_time)
    except KeyError:
        pass

# Try simple case first: print all jobs owned by a user, from a set of accounting files
username = sys.argv[1]
files=sys.argv[2:]

jobs = parser.parse_files(files)
print "%-20s  %-10s  %s  %s  %s  %s  %s" % ("Job Name","Username","Queue Time","Start Time","End Time","Wait Time","Run Time")
for j in jobs:
    try:
        if jobs[j]['user']==username:
            print_job(j,jobs[j])
    except KeyError:
        pass
